plugins { id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}
group = mod_group_id
version = mod_version

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories { mavenCentral() }

dependencies { implementation "net.neoforged:forge:${neoforge_version}" }

runs.configureEach {
    workingDirectory project.file('run')
    modSource project.sourceSets.main
}

processResources {
    filesMatching('META-INF/mods.toml') { expand(mod_id: mod_id, mod_name: mod_name, mod_version: mod_version) }
}
