package com.randombox.loot;
import net.minecraft.core.BlockPos; import net.minecraft.server.level.ServerLevel; import net.minecraft.server.level.ServerPlayer; import net.minecraft.world.entity.player.Player; import net.minecraft.world.level.block.entity.ChestBlockEntity; import net.minecraft.world.item.*; import net.minecraft.resources.ResourceLocation; import net.minecraft.core.registries.BuiltInRegistries; import net.minecraft.util.RandomSource; import java.util.*;
public class LootManager {
 public record Rarity(String name,int count,int quality,int color,float chance){} public static final Rarity[] R={new Rarity("普通",3,0,0xeeeeee,.50f),new Rarity("稀有",4,50,0x55ff55,.30f),new Rarity("史诗",5,100,0xaa55ff,.12f),new Rarity("传说",6,250,0xffff55,.065f),new Rarity("绝世",8,500,0xff5555,.015f)};
 private final Map<BlockPos,State> active=new HashMap<>(); private final Map<String,List<Entry>> tables=new HashMap<>();
 public LootManager(){ tables.put("minecraft:chests/simple_dungeon",List.of(new Entry(Items.IRON_INGOT,1,4,10),new Entry(Items.GOLD_INGOT,1,3,8),new Entry(Items.DIAMOND,1,2,2),new Entry(Items.BREAD,2,5,12))); }
 public boolean isOpening(BlockPos p){return active.containsKey(p);} public void begin(ServerLevel l,BlockPos p,Player pl,ChestBlockEntity c){ int forced=c.getPersistentData().getInt("randombox_forced"); Rarity r=forced>0 && forced<=5 ? R[forced-1] : choose(l.random); String table=c.getPersistentData().getString("randombox_table"); if(table.isEmpty())table="minecraft:chests/simple_dungeon"; active.put(p,new State(c,r,table,0,pl)); c.getPersistentData().putString("randombox_rarity",r.name); }
 private Rarity choose(RandomSource x){float n=x.nextFloat(),s=0;for(Rarity r:R){s+=r.chance;if(n<s)return r;}return R[0];}
 public void tick(ServerLevel l){ Iterator<Map.Entry<BlockPos,State>> it=active.entrySet().iterator(); while(it.hasNext()){var en=it.next();State s=en.getValue(); if(++s.ticks>=s.next){ if(s.index<s.r.count){ ItemStack out=pick(l.random,s); s.chest.setItem(s.index++,out); s.next=s.ticks+Math.max(12,(int)(24*(.5+l.random.nextFloat()))); particles(l,en.getKey(),s.r.color); } else {s.chest.getPersistentData().putBoolean("randombox_opened",true);it.remove();} } } }
 private ItemStack pick(RandomSource x,State s){List<Entry> a=tables.getOrDefault(s.table,tables.values().iterator().next());double total=a.stream().mapToDouble(e->e.weight).sum(),n=x.nextDouble()*total;for(Entry e:a)if((n-=e.weight)<=0)return new ItemStack(e.item,x.nextInt(e.max-e.min+1)+e.min);return new ItemStack(Items.BREAD);}
 private void particles(ServerLevel l,BlockPos p,int c){double r=(c>>16&255)/255.,g=(c>>8&255)/255.,b=(c&255)/255.;for(int i=0;i<10;i++)l.sendParticles(net.minecraft.core.particles.ParticleTypes.END_ROD,p.getX()+.5+(l.random.nextDouble()-.5)*2,p.getY()+1+l.random.nextDouble()*1.5,p.getZ()+.5+(l.random.nextDouble()-.5)*2,1,r,g,b,.02);}
 public void set(BlockPos p,int rarity,String table,ServerLevel l){var b=l.getBlockEntity(p);if(b instanceof ChestBlockEntity c){c.getPersistentData().putInt("randombox_forced",rarity);c.getPersistentData().putString("randombox_table",table);}}
 private static class State{ChestBlockEntity chest;Rarity r;String table;int index,ticks,next;Player player;State(ChestBlockEntity c,Rarity r,String t,int i,Player p){this.chest=c;this.r=r;table=t;player=p;}}
 public record Entry(Item item,int min,int max,double weight){}
}
